-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cama
(
    id_cama serial NOT NULL,
    id_habitacion integer NOT NULL,
    numero character varying(20) COLLATE pg_catalog."default" NOT NULL,
    estado character varying COLLATE pg_catalog."default" DEFAULT true,
    CONSTRAINT cama_pkey PRIMARY KEY (id_cama),
    CONSTRAINT cama_id_habitacion_numero_key UNIQUE (id_habitacion, numero)
);

CREATE TABLE IF NOT EXISTS public.cirugia
(
    id_cirugia serial NOT NULL,
    id_ingreso integer,
    id_quirofano integer,
    id_cirujano integer,
    procedimiento text COLLATE pg_catalog."default" NOT NULL,
    fecha_programada timestamp without time zone,
    fecha_realizacion timestamp without time zone,
    estado character varying(50) COLLATE pg_catalog."default",
    notas text COLLATE pg_catalog."default",
    CONSTRAINT cirugia_pkey PRIMARY KEY (id_cirugia)
);

CREATE TABLE IF NOT EXISTS public.consulta
(
    id_consulta serial NOT NULL,
    id_paciente integer NOT NULL,
    id_medico integer NOT NULL,
    id_consultorio integer,
    motivo text COLLATE pg_catalog."default" NOT NULL,
    observaciones text COLLATE pg_catalog."default",
    estado consulta_estado DEFAULT 'programada'::consulta_estado,
    fecha_programada timestamp without time zone,
    fecha_realizacion timestamp without time zone,
    duracion_min integer,
    tarifa numeric(12, 2) DEFAULT 0,
    creado_en timestamp without time zone DEFAULT now(),
    CONSTRAINT consulta_pkey PRIMARY KEY (id_consulta)
);

COMMENT ON TABLE public.consulta
    IS 'Tabla que unifica citas (agendadas) y consultas médicas realizadas.';

CREATE TABLE IF NOT EXISTS public.consultorio
(
    id_consultorio serial NOT NULL,
    codigo character varying(30) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    piso integer,
    CONSTRAINT consultorio_pkey PRIMARY KEY (id_consultorio),
    CONSTRAINT consultorio_codigo_key UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS public.detalle_factura
(
    id_detalle_factura serial NOT NULL,
    id_factura integer NOT NULL,
    id_servicio integer,
    descripcion text COLLATE pg_catalog."default",
    cantidad integer DEFAULT 1,
    precio_unitario numeric(12, 2),
    subtotal numeric(14, 2) GENERATED ALWAYS AS (((cantidad)::numeric * precio_unitario)) STORED,
    CONSTRAINT detalle_factura_pkey PRIMARY KEY (id_detalle_factura)
);

CREATE TABLE IF NOT EXISTS public.detalle_receta
(
    id_detalle serial NOT NULL,
    id_receta integer NOT NULL,
    id_medicamento integer NOT NULL,
    dosis character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cantidad integer,
    indicaciones text COLLATE pg_catalog."default",
    CONSTRAINT detalle_receta_pkey PRIMARY KEY (id_detalle)
);

CREATE TABLE IF NOT EXISTS public.especialidad
(
    id_especialidad serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    CONSTRAINT especialidad_pkey PRIMARY KEY (id_especialidad),
    CONSTRAINT especialidad_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.examen
(
    id_examen serial NOT NULL,
    id_paciente integer NOT NULL,
    id_solicitante integer,
    tipo_examen character varying(150) COLLATE pg_catalog."default" NOT NULL,
    fecha_orden timestamp without time zone DEFAULT now(),
    fecha_resultado timestamp without time zone,
    resultado text COLLATE pg_catalog."default",
    adjunto_ruta text COLLATE pg_catalog."default",
    estado character varying(50) COLLATE pg_catalog."default" DEFAULT 'solicitado'::character varying,
    CONSTRAINT examen_pkey PRIMARY KEY (id_examen)
);

CREATE TABLE IF NOT EXISTS public.factura
(
    id_factura serial NOT NULL,
    numero_factura character varying(50) COLLATE pg_catalog."default" NOT NULL,
    id_paciente integer,
    id_usuario integer,
    fecha_emision timestamp without time zone DEFAULT now(),
    total numeric(14, 2) DEFAULT 0,
    estado_pago character varying(30) COLLATE pg_catalog."default" DEFAULT 'pendiente'::character varying,
    CONSTRAINT factura_pkey PRIMARY KEY (id_factura),
    CONSTRAINT factura_numero_factura_key UNIQUE (numero_factura)
);

COMMENT ON TABLE public.factura
    IS 'Factura general con detalle de servicios facturados. Total se actualiza por trigger.';

CREATE TABLE IF NOT EXISTS public.habitacion
(
    id_habitacion serial NOT NULL,
    codigo character varying(30) COLLATE pg_catalog."default" NOT NULL,
    piso integer,
    tipo character varying(50) COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    CONSTRAINT habitacion_pkey PRIMARY KEY (id_habitacion),
    CONSTRAINT habitacion_codigo_key UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS public.historia_clinica
(
    id_historia serial NOT NULL,
    id_paciente integer NOT NULL,
    id_consulta integer,
    id_ingreso integer,
    resumen text COLLATE pg_catalog."default" NOT NULL,
    anotaciones text COLLATE pg_catalog."default",
    fecha_registro timestamp without time zone DEFAULT now(),
    CONSTRAINT historia_clinica_pkey PRIMARY KEY (id_historia)
);

COMMENT ON TABLE public.historia_clinica
    IS 'Registros clínicos asociados a consultas o ingresos hospitalarios.';

CREATE TABLE IF NOT EXISTS public.ingreso_hospitalario
(
    id_ingreso serial NOT NULL,
    id_paciente integer NOT NULL,
    id_cama integer,
    id_medico_responsable integer,
    fecha_ingreso timestamp without time zone DEFAULT now(),
    fecha_alta timestamp without time zone,
    motivo_ingreso text COLLATE pg_catalog."default" NOT NULL,
    estado ingreso_estado DEFAULT 'activo'::ingreso_estado,
    CONSTRAINT ingreso_hospitalario_pkey PRIMARY KEY (id_ingreso)
);

CREATE TABLE IF NOT EXISTS public.medicamento
(
    id_medicamento serial NOT NULL,
    nombre_comercial character varying(200) COLLATE pg_catalog."default" NOT NULL,
    principio_activo character varying(200) COLLATE pg_catalog."default",
    presentacion character varying(100) COLLATE pg_catalog."default",
    stock integer DEFAULT 0,
    precio_unitario numeric(12, 2),
    CONSTRAINT medicamento_pkey PRIMARY KEY (id_medicamento)
);

CREATE TABLE IF NOT EXISTS public.paciente
(
    id_paciente serial NOT NULL,
    nombres character varying(120) COLLATE pg_catalog."default" NOT NULL,
    apellidos character varying(120) COLLATE pg_catalog."default" NOT NULL,
    fecha_nacimiento date,
    sexo character(1) COLLATE pg_catalog."default",
    identificacion character varying(50) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(30) COLLATE pg_catalog."default",
    email character varying(150) COLLATE pg_catalog."default",
    direccion text COLLATE pg_catalog."default",
    creado_en timestamp without time zone DEFAULT now(),
    CONSTRAINT paciente_pkey PRIMARY KEY (id_paciente),
    CONSTRAINT paciente_identificacion_key UNIQUE (identificacion)
);

CREATE TABLE IF NOT EXISTS public.personal
(
    id_personal serial NOT NULL,
    nombres character varying(120) COLLATE pg_catalog."default" NOT NULL,
    apellidos character varying(120) COLLATE pg_catalog."default" NOT NULL,
    identificacion character varying(50) COLLATE pg_catalog."default" NOT NULL,
    id_usuario integer,
    id_especialidad integer,
    telefono character varying(30) COLLATE pg_catalog."default",
    email character varying(150) COLLATE pg_catalog."default",
    activo boolean DEFAULT true,
    creado_en timestamp without time zone DEFAULT now(),
    CONSTRAINT personal_pkey PRIMARY KEY (id_personal),
    CONSTRAINT personal_email_key UNIQUE (email),
    CONSTRAINT personal_id_usuario_key UNIQUE (id_usuario),
    CONSTRAINT personal_identificacion_key UNIQUE (identificacion)
);

CREATE TABLE IF NOT EXISTS public.quirofano
(
    id_quirofano serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    ubicacion text COLLATE pg_catalog."default",
    CONSTRAINT quirofano_pkey PRIMARY KEY (id_quirofano)
);

CREATE TABLE IF NOT EXISTS public.receta
(
    id_receta serial NOT NULL,
    id_paciente integer NOT NULL,
    id_medico integer NOT NULL,
    fecha_emision timestamp without time zone DEFAULT now(),
    instrucciones text COLLATE pg_catalog."default",
    CONSTRAINT receta_pkey PRIMARY KEY (id_receta)
);

CREATE TABLE IF NOT EXISTS public.rol
(
    id_rol serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    CONSTRAINT rol_pkey PRIMARY KEY (id_rol),
    CONSTRAINT rol_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.servicio
(
    id_servicio serial NOT NULL,
    codigo_servicio character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    precio_unitario numeric(12, 2) NOT NULL,
    CONSTRAINT servicio_pkey PRIMARY KEY (id_servicio),
    CONSTRAINT servicio_codigo_servicio_key UNIQUE (codigo_servicio)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id_usuario serial NOT NULL,
    username character varying(80) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id_rol integer NOT NULL,
    activo boolean DEFAULT true,
    fecha_creacion timestamp without time zone DEFAULT now(),
    CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario),
    CONSTRAINT usuarios_username_key UNIQUE (username)
);

ALTER TABLE IF EXISTS public.cama
    ADD CONSTRAINT cama_id_habitacion_fkey FOREIGN KEY (id_habitacion)
    REFERENCES public.habitacion (id_habitacion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.cirugia
    ADD CONSTRAINT cirugia_id_cirujano_fkey FOREIGN KEY (id_cirujano)
    REFERENCES public.personal (id_personal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.cirugia
    ADD CONSTRAINT cirugia_id_ingreso_fkey FOREIGN KEY (id_ingreso)
    REFERENCES public.ingreso_hospitalario (id_ingreso) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_cirugia_ingreso
    ON public.cirugia(id_ingreso);


ALTER TABLE IF EXISTS public.cirugia
    ADD CONSTRAINT cirugia_id_quirofano_fkey FOREIGN KEY (id_quirofano)
    REFERENCES public.quirofano (id_quirofano) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.consulta
    ADD CONSTRAINT consulta_id_consultorio_fkey FOREIGN KEY (id_consultorio)
    REFERENCES public.consultorio (id_consultorio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.consulta
    ADD CONSTRAINT consulta_id_medico_fkey FOREIGN KEY (id_medico)
    REFERENCES public.personal (id_personal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_consulta_medico
    ON public.consulta(id_medico);


ALTER TABLE IF EXISTS public.consulta
    ADD CONSTRAINT consulta_id_paciente_fkey FOREIGN KEY (id_paciente)
    REFERENCES public.paciente (id_paciente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_consulta_paciente
    ON public.consulta(id_paciente);


ALTER TABLE IF EXISTS public.detalle_factura
    ADD CONSTRAINT detalle_factura_id_factura_fkey FOREIGN KEY (id_factura)
    REFERENCES public.factura (id_factura) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_detallefactura_factura
    ON public.detalle_factura(id_factura);


ALTER TABLE IF EXISTS public.detalle_factura
    ADD CONSTRAINT detalle_factura_id_servicio_fkey FOREIGN KEY (id_servicio)
    REFERENCES public.servicio (id_servicio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.detalle_receta
    ADD CONSTRAINT detalle_receta_id_medicamento_fkey FOREIGN KEY (id_medicamento)
    REFERENCES public.medicamento (id_medicamento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.detalle_receta
    ADD CONSTRAINT detalle_receta_id_receta_fkey FOREIGN KEY (id_receta)
    REFERENCES public.receta (id_receta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_detallereceta_receta
    ON public.detalle_receta(id_receta);


ALTER TABLE IF EXISTS public.examen
    ADD CONSTRAINT examen_id_paciente_fkey FOREIGN KEY (id_paciente)
    REFERENCES public.paciente (id_paciente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_examen_paciente
    ON public.examen(id_paciente);


ALTER TABLE IF EXISTS public.examen
    ADD CONSTRAINT examen_id_solicitante_fkey FOREIGN KEY (id_solicitante)
    REFERENCES public.personal (id_personal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.factura
    ADD CONSTRAINT factura_id_paciente_fkey FOREIGN KEY (id_paciente)
    REFERENCES public.paciente (id_paciente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_factura_paciente
    ON public.factura(id_paciente);


ALTER TABLE IF EXISTS public.factura
    ADD CONSTRAINT factura_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.historia_clinica
    ADD CONSTRAINT historia_clinica_id_consulta_fkey FOREIGN KEY (id_consulta)
    REFERENCES public.consulta (id_consulta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.historia_clinica
    ADD CONSTRAINT historia_clinica_id_ingreso_fkey FOREIGN KEY (id_ingreso)
    REFERENCES public.ingreso_hospitalario (id_ingreso) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.historia_clinica
    ADD CONSTRAINT historia_clinica_id_paciente_fkey FOREIGN KEY (id_paciente)
    REFERENCES public.paciente (id_paciente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.ingreso_hospitalario
    ADD CONSTRAINT ingreso_hospitalario_id_cama_fkey FOREIGN KEY (id_cama)
    REFERENCES public.cama (id_cama) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.ingreso_hospitalario
    ADD CONSTRAINT ingreso_hospitalario_id_medico_responsable_fkey FOREIGN KEY (id_medico_responsable)
    REFERENCES public.personal (id_personal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.ingreso_hospitalario
    ADD CONSTRAINT ingreso_hospitalario_id_paciente_fkey FOREIGN KEY (id_paciente)
    REFERENCES public.paciente (id_paciente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_ingreso_paciente
    ON public.ingreso_hospitalario(id_paciente);


ALTER TABLE IF EXISTS public.personal
    ADD CONSTRAINT personal_id_especialidad_fkey FOREIGN KEY (id_especialidad)
    REFERENCES public.especialidad (id_especialidad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.personal
    ADD CONSTRAINT personal_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS personal_id_usuario_key
    ON public.personal(id_usuario);


ALTER TABLE IF EXISTS public.receta
    ADD CONSTRAINT receta_id_medico_fkey FOREIGN KEY (id_medico)
    REFERENCES public.personal (id_personal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.receta
    ADD CONSTRAINT receta_id_paciente_fkey FOREIGN KEY (id_paciente)
    REFERENCES public.paciente (id_paciente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_receta_paciente
    ON public.receta(id_paciente);


ALTER TABLE IF EXISTS public.usuarios
    ADD CONSTRAINT usuarios_id_rol_fkey FOREIGN KEY (id_rol)
    REFERENCES public.rol (id_rol) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

END;