services:
  server:
    build: ./server
    container_name: server
    ports:
      - "3001:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    depends_on:
      postgres:
        condition: service_healthy

  client:
    build: ./client
    container_name: client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
  postgres:
    image: postgres:16
    container_name: postgres-hospital
    restart: always
    environment:
      POSTGRES_DB: SistemaHospitalario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-Admi123}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d SistemaHospitalario"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./SisHospital.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data:

