openapi: 3.0.0

info:
  title: API de Pacientes
  version: 1.0.0
  description: Contrato de API para la gestión de pacientes usando arquitectura hexagonal en Node.js.

servers:
  - url: http://localhost:3002/api/v1

tags:
  - name: Patients
    description: Operaciones relacionadas con pacientes

paths:
  /patients:

    get:
      tags:
        - Patients
      summary: Listar pacientes
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de pacientes obtenida correctamente

    post:
      tags:
        - Patients
      summary: Registrar paciente
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CrearPacienteRequest'
      responses:
        '201':
          description: Paciente registrado correctamente

    delete:
      tags:
        - Patients
      summary: Eliminar paciente
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EliminarPacienteRequest'
      responses:
        '200':
          description: Paciente eliminado correctamente

components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    Patient:
      type: object
      properties:

        id_paciente:
          type: integer
          example: 1

        nombre:
          type: string
          example: Juan

        apellido:
          type: string
          example: Pérez

        cedula:
          type: string
          example: "0701234567"

        fecha_nacimiento:
          type: string
          format: date
          example: "2000-05-15"

        telefono:
          type: string
          example: "0999999999"

        direccion:
          type: string
          example: "Machala, El Oro"

    CrearPacienteRequest:
      type: object
      required:
        - nombre
        - apellido
        - cedula
      properties:

        nombre:
          type: string
          example: Juan

        apellido:
          type: string
          example: Pérez

        cedula:
          type: string
          example: "0701234567"

        fecha_nacimiento:
          type: string
          format: date
          example: "2000-05-15"

        telefono:
          type: string
          example: "0999999999"

        direccion:
          type: string
          example: "Machala, El Oro"

    EliminarPacienteRequest:
      type: object
      required:
        - id_paciente
      properties:

        id_paciente:
          type: integer
          example: 1